[package]
name = "rustree"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]
edition = "2018"

[dependencies]
rusoto_s3 = "0.39.0"
rusoto_core = "0.39.0"
structopt = "0.2.16"
regex = "1.1.7"
lazy_static = "1.3.0"
futures = "0.1.27"
rusoto_credential = "0.39.0"
